version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodbconfig:/data/configdb
      - ./mongodb/script.js:/docker-entrypoint-initdb.d/script.js
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: P@ssw0rd

volumes:
  mongodbconfig: